.TH TEMPLATE 1
.SH NAME
TEMPLATE \- A template for more manpages
.SH SYNOPSIS
.B template
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B template
A template for more manpages.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.